Rimed\BlogBundle\Entity\BaseCategory:
    type: entity
    table: blog_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    
    fields:
        name:
            type: string
        enabled:
            type: boolean
            default: false
        slug:
            type: string

        description:
            type: string
            nullable: true
        count:         
            type: integer
            default: 0

        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    lifecycleCallbacks:
        prePersist: [ prePersist ]
        preUpdate: [ preUpdate ]
